
import { League_Spartan, Urbanist, Outfit } from "next/font/google";

// load the fonts
const spartan = League_Spartan({ subsets: ["latin"], variable: "--font-spartan" });
const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });
import "./globals.css";


import Footer from "./components/Footer";
import Authlayout from "./components/Auth/Authlayout";

export const metadata = {
  title: "Medison Ai Assistence",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spartan.variable} ${urbanist.variable} ${outfit.variable}`}
      >
     

       <Authlayout> {children}</Authlayout>
       
         <Footer/>
      </body>
    </html>
  );
}
